// E5 taxonomy: T1 oracle (engine number vs an independent number)
// INDEPENDENT reference cross-checks for the bond kernels — validating penny-perfection against
// references OTHER than QuantLib, and QuantLib-FREE (so this runs in the engine's own gate binary):
//
//   1. Excel / OpenFormula PRICE & YIELD (basis 1 = Actual/Actual) — the spreadsheet street convention,
//      reimplemented here from its published formula (a different algebra than our Horner kernel). Matching
//      it catches implementation bugs a single oracle could hide.
//   2. 31 CFR Part 356 Appendix B — the OFFICIAL US Treasury price/yield formula, including the SHORT
//      first-coupon (when-issued) case, reimplemented from the regulation. NB App B is a DIFFERENT
//      convention from what our kernel implements — see the note below — so this test pins the exact,
//      understood relationship between the two, not equality.
//   3. An OPTIONAL golden CSV (tests/golden/bond_reference.csv) generated by an external library
//      (Rateslib `calc_mode="us_gb"` and `"ust_31bii"`) via tools/bond_reference/gen_golden.py.
//      Skipped (GTEST_SKIP) if the file is absent, so the gate is green without the external tool but
//      pins the numbers exactly when it is present.
//
// ===================================================================================================
// STREET vs TREASURY (31 CFR App B) DISCOUNTING — the one convention difference, stated once.
// ===================================================================================================
// Both conventions agree on the cashflows, on accrued, and on the whole coupon polynomial
// Q(v) = Σ CF_k·v^k. They differ ONLY in how the FRACTIONAL first period w is discounted:
//
//   STREET (ours, QuantLib BondFunctions/Compounded, Rateslib "us_gb"):   dirty = Q(v) · v^w
//   TREASURY, 31 CFR Part 356 App B (Rateslib "ust_31bii"/"us_gb_tsy"):   dirty = Q(v) / (1 + w·y/f)
//
// The regulation is uniform on this: every sub-case in App B Section II (regular first period, short
// first, long first, and the three reopened cases) is written "P[1 + (r/s)(i/2)] = ..." — SIMPLE
// interest over r/s, never a compound (1+i/2)^(r/s). So
//
//   dirty_AppB = dirty_street · (1 + y/f)^w / (1 + w·y/f)
//
// which is an exact identity, not an approximation. On a 6y note at y=2% (w = 30/184) it is ~7e-6 of
// price — ~0.7 bp — so the two are NOT interchangeable at the tolerances this repo works to.
//
// THE KERNEL NOW IMPLEMENTS BOTH, selected by pricing::YieldConvention (see the table in
// pricing/bond.hpp). `build::us_treasury` is STREET (compound stub, simple once only the final coupon
// remains); `build::us_treasury_tsy` is the App B / Treasury method (simple stub always); the plain
// `fixed_rate_bond` default is compound-everywhere, i.e. the UK gilt / French OAT mode. The WI builders
// mirror the same pair. Both have QuantLib oracles -- Compounded and SimpleThenCompounded respectively.
//
// See docs/bond-pricing.md §"Cross-validation beyond QuantLib".

#include <gtest/gtest.h>

#include <cmath>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "swaps/build/bond.hpp"
#include "swaps/pricing/bond.hpp"

namespace px = swaps::pricing;
namespace bld = swaps::build;

namespace {

// ---- 1. Excel / OpenFormula PRICE & YIELD (basis Act/Act), for a REGULAR bond -----------------------
// PRICE (per unit notional) = Σ_{k=1}^N c·v^{(k-1)+w} + v^{(N-1)+w} − c·(1−w),  v = 1/(1+y/f),
// w = DSC/E = (next coupon − settle)/(next coupon − prev coupon). This is Excel's PRICE(...,basis=1).
double excel_clean(const bld::BuiltBond& b, const bld::Date& settle, double coupon, int freq, double y) {
  const double w = double(b.next_coupon - settle) / double(b.next_coupon - b.prev_coupon);
  const int N = static_cast<int>(b.yield.flows.size());
  const double c = coupon / freq, v = 1.0 / (1.0 + y / freq);
  double dirty = 0.0;
  for (int k = 1; k <= N; ++k) dirty += c * std::pow(v, (k - 1) + w);
  dirty += std::pow(v, (N - 1) + w);        // redemption 1.0
  return dirty - c * (1.0 - w);             // clean = dirty − accrued
}
double excel_yield(const bld::BuiltBond& b, const bld::Date& settle, double coupon, int freq,
                   double target_clean) {
  double y = 0.05;
  for (int it = 0; it < 100; ++it) {
    const double h = 1e-7;
    const double f0 = excel_clean(b, settle, coupon, freq, y) - target_clean;
    if (std::abs(f0) < 1e-14) break;
    const double d = (excel_clean(b, settle, coupon, freq, y + h) -
                      excel_clean(b, settle, coupon, freq, y - h)) / (2 * h);
    y -= f0 / d;
  }
  return y;
}

TEST(BondReference, ExcelOpenFormulaPriceYield) {
  const bld::Date val = bld::Date::ymd(2024, 1, 15), settle = bld::Date::ymd(2024, 1, 16),
                 issue = bld::Date::ymd(2019, 8, 15);
  for (int m : {2028, 2031, 2034, 2044}) {
    for (double coupon : {0.02, 0.045, 0.07}) {
      const bld::BuiltBond b = bld::us_treasury(val, settle, issue, bld::Date::ymd(m, 2, 15), coupon);
      for (double y : {0.02, 0.04, 0.06}) {
        const double clean_ref = excel_clean(b, settle, coupon, 2, y);
        EXPECT_NEAR(px::bond_clean_from_yield(b.yield, y), clean_ref, 1e-12) << "price m=" << m;
        // and the inverse
        EXPECT_NEAR(px::bond_yield_from_clean(b.yield, clean_ref),
                    excel_yield(b, settle, coupon, 2, clean_ref), 1e-11) << "yield m=" << m;
      }
    }
  }
}

// ---- 2. 31 CFR Part 356 Appendix B — short-first-coupon (when-issued) reference ---------------------
// App B Section II.B (short first interest payment period), verbatim:
//     P[1 + (r/s)(i/2)] = (C/2)(r/s) + (C/2)·a_n + 100·v^n
// i.e. the coupon polynomial Q(v) (whose FIRST coupon is prorated by r/s — the "daily interest decimal")
// divided by the SIMPLE factor [1 + (r/s)(i/2)].  Here r/s = (first_coupon − settle)/E = w0, and for a new
// issue settling on the dated date r/s is also the proration factor s.
//
// Our kernel gives Q(v)·v^{w0} (street). This test therefore asserts TWO things:
//   (a) the coupon polynomial Q — hence the App B PRORATION our WI builder applies — is exactly right;
//   (b) our price and the regulation's price are related by the exact convention factor above.
// The old version of this test reimplemented v^{w0} and compared it to our v^{w0}: a tautology that could
// not have caught the convention difference. It does now.
TEST(BondReference, CfrAppendixBShortFirstCoupon) {
  const bld::Date val = bld::Date::ymd(2024, 6, 14), dated = bld::Date::ymd(2024, 6, 15),
                 fcpn = bld::Date::ymd(2024, 11, 15), qp = bld::Date::ymd(2024, 5, 15),
                 mat = bld::Date::ymd(2034, 11, 15);
  const double coupon = 0.045, f = 2.0;
  const bld::BuiltBond wi = bld::us_treasury_wi(val, dated, fcpn, mat, coupon);  // settle == dated (new issue)
  const double E = double(fcpn - qp), s = double(fcpn - dated) / E, w0 = double(fcpn - dated) / E;
  const int N = static_cast<int>(wi.yield.flows.size());
  const double c = coupon / f;
  for (double y : {0.03, 0.047, 0.06}) {
    const double v = 1.0 / (1.0 + y / f);
    // Q(v): the App B right-hand side. First coupon prorated by r/s, then regular coupons, then redemption.
    double Q = c * s;
    for (int j = 1; j < N - 1; ++j) Q += c * std::pow(v, j);
    Q += (c + 1.0) * std::pow(v, N - 1);
    // (a) the polynomial (and the proration in it) matches ours exactly.
    EXPECT_NEAR(px::bond_dirty_from_yield(wi.yield, y), Q * std::pow(v, w0), 1e-12) << "Q, y=" << y;
    // (b) the regulation's price is ours times the exact street->Treasury convention factor.
    const double appB = Q / (1.0 + w0 * y / f);
    EXPECT_NEAR(px::bond_dirty_from_yield(wi.yield, y) * std::pow(1.0 + y / f, w0) / (1.0 + w0 * y / f),
                appB, 1e-12) << "AppB, y=" << y;
    // ... and the two conventions genuinely differ at a magnitude that matters (>1e-6 of price here).
    EXPECT_GT(std::abs(appB - px::bond_dirty_from_yield(wi.yield, y)), 1e-6) << "y=" << y;
  }
  EXPECT_NEAR(wi.accrued, 0.0, 1e-15);  // new issue settles on the dated date => zero accrued
}

// ---- 3. Optional external-library golden (Rateslib), skipped if absent ----------------------------
// CSV columns (header row): mode,value_date,settle,issue,maturity,coupon,yield,clean,dirty,accrued
// All dates ISO YYYY-MM-DD; coupon/yield as decimals; prices per unit notional (par = 1.0).
// `mode` is the Rateslib calc_mode the row was priced under:
//   us_gb      -> the street convention our kernel implements: assert EQUALITY.
//   ust_31bii  -> the 31 CFR App B Treasury convention: assert our price times the exact convention
//                 factor (1+y/f)^w/(1+w·y/f) equals it. This pins the divergence as understood rather
//                 than tolerating it, and would catch any drift in EITHER convention.
TEST(BondReference, ExternalGoldenIfPresent) {
  const std::string path = std::string(SWAPS_GOLDEN_DIR) + "/bond_reference.csv";
  std::ifstream in(path);
  if (!in) GTEST_SKIP() << "no external golden at " << path
                        << " (generate with tools/bond_reference/gen_golden.py using Rateslib)";
  std::string line;
  std::getline(in, line);  // header
  int rows = 0, street_rows = 0, tsy_rows = 0;
  while (std::getline(in, line)) {
    if (line.empty()) continue;
    std::stringstream ss(line);
    std::string mode, vd, st, is, ma, cp, yl, cl, di, ac;
    std::getline(ss, mode, ','); std::getline(ss, vd, ','); std::getline(ss, st, ',');
    std::getline(ss, is, ','); std::getline(ss, ma, ','); std::getline(ss, cp, ',');
    std::getline(ss, yl, ','); std::getline(ss, cl, ','); std::getline(ss, di, ',');
    std::getline(ss, ac, ',');
    const bld::Date settle = bld::Date::from_iso(st);
    const bld::Date vdate = bld::Date::from_iso(vd), iss = bld::Date::from_iso(is),
                    mat = bld::Date::from_iso(ma);
    const double cpn = std::stod(cp), y = std::stod(yl);
    if (mode == "us_gb") {
      // STREET: build::us_treasury. None of these rows settles in the final coupon period, so the
      // street and plain-compound forms coincide here; the final-period switch is pinned separately by
      // BondOracle.StreetSwitchesToSimpleStubInTheFinalPeriod.
      const bld::BuiltBond b = bld::us_treasury(vdate, settle, iss, mat, cpn);
      EXPECT_NEAR(b.accrued, std::stod(ac), 1e-9) << "accrued row " << rows << " (" << mode << ")";
      EXPECT_NEAR(px::bond_clean_from_yield(b.yield, y), std::stod(cl), 1e-9) << "clean row " << rows;
      EXPECT_NEAR(px::bond_dirty_from_yield(b.yield, y), std::stod(di), 1e-9) << "dirty row " << rows;
      ++street_rows;
    } else if (mode == "ust_31bii") {
      // TREASURY METHOD: build::us_treasury_tsy prices the App B convention directly, so this is a plain
      // equality against the external library -- no conversion factor applied on our side.
      const bld::BuiltBond b = bld::us_treasury_tsy(vdate, settle, iss, mat, cpn);
      EXPECT_NEAR(b.accrued, std::stod(ac), 1e-9) << "accrued row " << rows << " (" << mode << ")";
      EXPECT_NEAR(px::bond_clean_from_yield(b.yield, y), std::stod(cl), 1e-9) << "clean(31bii) row " << rows;
      EXPECT_NEAR(px::bond_dirty_from_yield(b.yield, y), std::stod(di), 1e-9) << "dirty(31bii) row " << rows;
      // ... and the two conventions are genuinely different numbers on this same bond.
      EXPECT_GT(std::abs(px::bond_dirty_from_yield(b.yield, y) -
                         px::bond_dirty_from_yield(bld::us_treasury(vdate, settle, iss, mat, cpn).yield, y)),
                1e-6) << "row " << rows;
      ++tsy_rows;
    } else {
      ADD_FAILURE() << "unknown calc mode '" << mode << "' in " << path << " row " << rows;
    }
    ++rows;
  }
  EXPECT_GT(street_rows, 0);
  EXPECT_GT(tsy_rows, 0);
}

}  // namespace
