// INDEPENDENT reference cross-checks for the bond kernels — validating penny-perfection against
// references OTHER than QuantLib, and QuantLib-FREE (so this runs in the engine's own gate binary):
//
//   1. Excel / OpenFormula PRICE & YIELD (basis 1 = Actual/Actual) — the spreadsheet street convention,
//      reimplemented here from its published formula (a different algebra than our Horner kernel). Matching
//      it catches implementation bugs a single oracle could hide.
//   2. 31 CFR Part 356 Appendix B — the OFFICIAL US Treasury price/yield formula, including the SHORT
//      first-coupon (when-issued) case, reimplemented from the regulation.
//   3. An OPTIONAL golden CSV (tests/golden/bond_reference.csv) generated by an external library
//      (Rateslib `calc_mode="ust_31bii"`/`us_gb`, or Bloomberg) via tools/bond_reference/gen_golden.py.
//      Skipped (GTEST_SKIP) if the file is absent, so the gate is green without the external tool but
//      pins the numbers exactly when it is present.
//
// See docs/bond-pricing.md §"Cross-validation beyond QuantLib".

#include <gtest/gtest.h>

#include <cmath>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "swaps/build/bond.hpp"
#include "swaps/pricing/bond.hpp"

namespace px = swaps::pricing;
namespace bld = swaps::build;

namespace {

// ---- 1. Excel / OpenFormula PRICE & YIELD (basis Act/Act), for a REGULAR bond -----------------------
// PRICE (per unit notional) = Σ_{k=1}^N c·v^{(k-1)+w} + v^{(N-1)+w} − c·(1−w),  v = 1/(1+y/f),
// w = DSC/E = (next coupon − settle)/(next coupon − prev coupon). This is Excel's PRICE(...,basis=1).
double excel_clean(const bld::BuiltBond& b, const bld::Date& settle, double coupon, int freq, double y) {
  const double w = double(b.next_coupon - settle) / double(b.next_coupon - b.prev_coupon);
  const int N = static_cast<int>(b.yield.flows.size());
  const double c = coupon / freq, v = 1.0 / (1.0 + y / freq);
  double dirty = 0.0;
  for (int k = 1; k <= N; ++k) dirty += c * std::pow(v, (k - 1) + w);
  dirty += std::pow(v, (N - 1) + w);        // redemption 1.0
  return dirty - c * (1.0 - w);             // clean = dirty − accrued
}
double excel_yield(const bld::BuiltBond& b, const bld::Date& settle, double coupon, int freq,
                   double target_clean) {
  double y = 0.05;
  for (int it = 0; it < 100; ++it) {
    const double h = 1e-7;
    const double f0 = excel_clean(b, settle, coupon, freq, y) - target_clean;
    if (std::abs(f0) < 1e-14) break;
    const double d = (excel_clean(b, settle, coupon, freq, y + h) -
                      excel_clean(b, settle, coupon, freq, y - h)) / (2 * h);
    y -= f0 / d;
  }
  return y;
}

TEST(BondReference, ExcelOpenFormulaPriceYield) {
  const bld::Date val = bld::Date::ymd(2024, 1, 15), settle = bld::Date::ymd(2024, 1, 16),
                 issue = bld::Date::ymd(2019, 8, 15);
  for (int m : {2028, 2031, 2034, 2044}) {
    for (double coupon : {0.02, 0.045, 0.07}) {
      const bld::BuiltBond b = bld::us_treasury(val, settle, issue, bld::Date::ymd(m, 2, 15), coupon);
      for (double y : {0.02, 0.04, 0.06}) {
        const double clean_ref = excel_clean(b, settle, coupon, 2, y);
        EXPECT_NEAR(px::bond_clean_from_yield(b.yield, y), clean_ref, 1e-12) << "price m=" << m;
        // and the inverse
        EXPECT_NEAR(px::bond_yield_from_clean(b.yield, clean_ref),
                    excel_yield(b, settle, coupon, 2, clean_ref), 1e-11) << "yield m=" << m;
      }
    }
  }
}

// ---- 2. 31 CFR Part 356 Appendix B — short-first-coupon (when-issued) reference ---------------------
// dirty = c·s·v^{w0} + Σ_{j=1}^{N-1} c·v^{w0+j} + v^{w0+N-1},  clean = dirty − c·a, with s the short
// coupon factor (first_coupon−dated)/E, a the accrued fraction (settle−dated)/E, w0 = (first_coupon−settle)/E.
TEST(BondReference, CfrAppendixBShortFirstCoupon) {
  const bld::Date val = bld::Date::ymd(2024, 6, 14), dated = bld::Date::ymd(2024, 6, 15),
                 fcpn = bld::Date::ymd(2024, 11, 15), qp = bld::Date::ymd(2024, 5, 15),
                 mat = bld::Date::ymd(2034, 11, 15);
  const double coupon = 0.045, f = 2.0;
  const bld::BuiltBond wi = bld::us_treasury_wi(val, dated, fcpn, mat, coupon);  // settle == dated (new issue)
  const double E = double(fcpn - qp), s = double(fcpn - dated) / E, w0 = double(fcpn - dated) / E;
  const int N = static_cast<int>(wi.yield.flows.size());
  const double c = coupon / f;
  for (double y : {0.03, 0.047, 0.06}) {
    const double v = 1.0 / (1.0 + y / f);
    double dirty = c * s * std::pow(v, w0);
    for (int j = 1; j < N - 1; ++j) dirty += c * std::pow(v, w0 + j);
    dirty += (c + 1.0) * std::pow(v, w0 + (N - 1));
    EXPECT_NEAR(px::bond_dirty_from_yield(wi.yield, y), dirty, 1e-12) << "y=" << y;
  }
  EXPECT_NEAR(wi.accrued, 0.0, 1e-15);  // new issue settles on the dated date => zero accrued
}

// ---- 3. Optional external-library golden (Rateslib / Bloomberg), skipped if absent -----------------
// CSV columns (header row): value_date,settle,issue,maturity,coupon,yield,clean,dirty,accrued
// All dates ISO YYYY-MM-DD; coupon/yield as decimals; prices per unit notional (par = 1.0).
TEST(BondReference, ExternalGoldenIfPresent) {
  const std::string path = std::string(SWAPS_GOLDEN_DIR) + "/bond_reference.csv";
  std::ifstream in(path);
  if (!in) GTEST_SKIP() << "no external golden at " << path
                        << " (generate with tools/bond_reference/gen_golden.py using Rateslib)";
  std::string line;
  std::getline(in, line);  // header
  int rows = 0;
  while (std::getline(in, line)) {
    if (line.empty()) continue;
    std::stringstream ss(line);
    std::string vd, st, is, ma, cp, yl, cl, di, ac;
    std::getline(ss, vd, ','); std::getline(ss, st, ','); std::getline(ss, is, ',');
    std::getline(ss, ma, ','); std::getline(ss, cp, ','); std::getline(ss, yl, ',');
    std::getline(ss, cl, ','); std::getline(ss, di, ','); std::getline(ss, ac, ',');
    const bld::BuiltBond b = bld::us_treasury(bld::Date::from_iso(vd), bld::Date::from_iso(st),
                                              bld::Date::from_iso(is), bld::Date::from_iso(ma),
                                              std::stod(cp));
    const double y = std::stod(yl);
    EXPECT_NEAR(px::bond_clean_from_yield(b.yield, y), std::stod(cl), 1e-9) << "clean row " << rows;
    EXPECT_NEAR(px::bond_dirty_from_yield(b.yield, y), std::stod(di), 1e-9) << "dirty row " << rows;
    EXPECT_NEAR(b.accrued, std::stod(ac), 1e-9) << "accrued row " << rows;
    ++rows;
  }
  EXPECT_GT(rows, 0);
}

}  // namespace
