// Phase 2 calibration gate: global Levenberg-Marquardt over the knot forwards.
//
// Two properties, matching the over-determined design (CLAUDE.md §2/§3):
//   (a) Recovery: if the market quotes are generated by pricing instruments off a KNOWN curve,
//       calibration recovers that curve (residual -> 0, x -> known). This tests solver + kernel +
//       residual wiring end to end, with an exactly-attainable optimum.
//   (b) Stationarity: on the actual (over-determined) market quotes the residual is non-zero, so we
//       assert first-order optimality ||J^T r||_inf ~ 0 -- NOT exact repricing.

#include <gtest/gtest.h>
#include <ql/quantlib.hpp>

#include <Eigen/Core>
#include <cmath>

#include "reference_curve.hpp"
#include "swaps/calibration/lm.hpp"
#include "swaps/calibration/problem.hpp"

using namespace QuantLib;
namespace rb = swaps::refbuild;
namespace cal = swaps::calibration;
namespace rm = swaps::refmkt;

namespace {

Eigen::VectorXd reference_x() {
  Eigen::VectorXd x(rm::n_knots);
  int i = 0;
  for (double f : rm::reference_front_forwards) x[i++] = f;
  for (double g : rm::reference_back_forwards) x[i++] = g;
  return x;
}

// A calibration problem whose market quotes are exactly the model quotes at the reference curve,
// so the global minimum sits at the reference forwards with zero residual.
cal::CalibrationProblem self_consistent_problem(const rb::Market& mk) {
  cal::CalibrationProblem p = rb::build_problem(mk);
  rb::Curve ref = rb::reference_curve(mk);
  for (auto& s : p.swaps) s.market_rate = swaps::pricing::ois_par_rate<double>(s.sched, ref);
  for (auto& cf : p.comp_futs)
    cf.market_rate = swaps::pricing::compounded_future_rate<double>(cf.sched, ref) + cf.convexity;
  for (auto& a : p.avg_futs)
    a.market_rate = swaps::pricing::averaged_future_rate<double>(a.sched, ref) + a.convexity;
  return p;
}

}  // namespace

struct Calibration : ::testing::Test {
  RelinkableHandle<YieldTermStructure> h;
  rb::Market mk = rb::build_market(h);
};

TEST_F(Calibration, ProblemDimensionsAreOverDetermined) {
  cal::CalibrationProblem p = rb::build_problem(mk);
  EXPECT_EQ(p.n_knots(), rm::n_knots);         // 23
  EXPECT_EQ(p.n_residuals(), rm::n_instruments);  // 29
  EXPECT_GT(p.n_residuals(), p.n_knots());
}

TEST_F(Calibration, RecoversTheGeneratingCurve) {
  const cal::CalibrationProblem p = self_consistent_problem(mk);
  const Eigen::VectorXd xref = reference_x();

  // Residual is exactly zero at the reference forwards (construction check).
  EXPECT_LT(p.residuals<double>(xref).cwiseAbs().maxCoeff(), 1e-12);

  // Start well away from the answer: +40bp parallel plus an alternating tilt.
  Eigen::VectorXd x0 = xref;
  for (int i = 0; i < x0.size(); ++i) x0[i] += 0.0040 + (i % 2 ? 0.0015 : -0.0015);

  const cal::CalibrationResult res = cal::calibrate(p, x0);
  std::cout << "  [recover] iters=" << res.iterations << " rms=" << res.rms_residual
            << " ||x*-xref||_inf=" << (res.x - xref).cwiseAbs().maxCoeff()
            << " stationarity=" << res.stationarity << "\n";

  EXPECT_LT(res.rms_residual, 1e-9) << "should reach the zero-residual optimum";
  EXPECT_LT((res.x - xref).cwiseAbs().maxCoeff(), 1e-7) << "should recover the generating forwards";
}

TEST_F(Calibration, ReachesStationarityOnOverDeterminedMarket) {
  const cal::CalibrationProblem p = rb::build_problem(mk);  // real quotes; residual != 0
  const cal::CalibrationResult res = cal::calibrate(p, reference_x());

  std::cout << "  [market] iters=" << res.iterations << " rms=" << res.rms_residual
            << " stationarity=" << res.stationarity << "\n";

  EXPECT_GT(res.rms_residual, 1e-6) << "over-determined market must retain a non-zero residual";
  EXPECT_LT(res.stationarity, 1e-6) << "first-order optimality ||J^T r||_inf must vanish";
}
