#pragma once
// curve/parametric.hpp — PARAMETRIC term-structure models: a smooth curve generated by a FEW parameters,
// the bond-RV fair-value-curve workhorses. Where a ModularCurve (curve_module.hpp) is a free-knot spline
// (one forward per pillar — flexible, but the knots move date to date), a parametric model has a small,
// economically-interpretable, TIME-STABLE parameter set, so the per-bond residual off the fitted curve is a
// robust richness/cheapness signal and the parameter time series is itself the object of study.
//
// Both are the SAME kind of object to the engine: a Scalar-templated curve exposing `Scalar discount(double
// t)` built from a parameter vector via `set_params`. So a parametric model is a DROP-IN for the spline in
// calibration::GovvieBondFit — the identical least-squares LM + AAD Jacobian + CompiledBondBook z-spread RV
// ladder drive it, no new machinery. Scalar = double prices; Scalar = ad::Dual yields d(price)/d(param), so
// the minimum-pricing-error fit over a whole universe is one templated calibrate().
//
// NelsonSiegel (3 params + a fixed decay τ) and Svensson (4 params + two decays) are the standard forms —
// and the restricted affine models behind the Diebold-Li dynamic Nelson-Siegel factor reading (level /
// slope / curvature). A GENERAL affine / ATSM curve — custom factor loadings A(t), B(t), y(t)=A+B·X — is
// the same interface with different loadings, so it plugs into GovvieBondFit unchanged when added.
//
// The decays τ are held as fixed DOUBLE hyperparameters here (the usual choice for stability — many official
// curves fix them and fit only the linear betas, which also keeps the zero-rate LINEAR in the free params so
// the fit is well conditioned). Freeing τ is a later option (reparameterize as exp(θ) to keep τ>0).

#include <cmath>

#include <Eigen/Core>

namespace swaps::curve {

// Nelson-Siegel zero rate y(t) = β0 + β1·L1(t) + β2·(L1(t) − e^{−t/τ}),  L1(t) = (1−e^{−t/τ})/(t/τ).
// β0 = long level, β1 = short-end slope, β2 = curvature (medium-term hump). DF(t) = exp(−y(t)·t).
template <class Scalar>
class NelsonSiegel {
 public:
  explicit NelsonSiegel(double tau = 2.0) : tau_(tau) { b_.setZero(3); }
  static constexpr int n_params() { return 3; }

  void set_params(const Eigen::Matrix<Scalar, Eigen::Dynamic, 1>& p) { b_ = p.head(3); }

  // Continuously-compounded zero rate. The loadings are pure functions of t and the fixed τ (plain double),
  // so y is LINEAR in the Scalar params — AAD derivatives w.r.t. β are exactly the loadings.
  Scalar zero_rate(double t) const {
    if (t <= 0.0) return b_[0] + b_[1];
    const double x = t / tau_;
    const double e = std::exp(-x);
    const double L1 = (1.0 - e) / x;
    return b_[0] + b_[1] * Scalar(L1) + b_[2] * Scalar(L1 - e);
  }
  Scalar discount(double t) const {
    if (t <= 0.0) return Scalar(1.0);
    using std::exp;
    return exp(-zero_rate(t) * Scalar(t));
  }

 private:
  Eigen::Matrix<Scalar, Eigen::Dynamic, 1> b_;  // [β0, β1, β2]
  double tau_;
};

// Svensson: Nelson-Siegel + a second curvature term with its own decay τ2 (a second hump — the extra
// flexibility for a rich long end). y(t) = β0 + β1·L1(τ1) + β2·(L1(τ1) − e^{−t/τ1}) + β3·(L1(τ2) − e^{−t/τ2}).
template <class Scalar>
class Svensson {
 public:
  Svensson(double tau1 = 2.0, double tau2 = 5.0) : tau1_(tau1), tau2_(tau2) { b_.setZero(4); }
  static constexpr int n_params() { return 4; }

  void set_params(const Eigen::Matrix<Scalar, Eigen::Dynamic, 1>& p) { b_ = p.head(4); }

  Scalar zero_rate(double t) const {
    if (t <= 0.0) return b_[0] + b_[1];
    const double x1 = t / tau1_, e1 = std::exp(-x1), L1 = (1.0 - e1) / x1;
    const double x2 = t / tau2_, e2 = std::exp(-x2), L2 = (1.0 - e2) / x2;
    return b_[0] + b_[1] * Scalar(L1) + b_[2] * Scalar(L1 - e1) + b_[3] * Scalar(L2 - e2);
  }
  Scalar discount(double t) const {
    if (t <= 0.0) return Scalar(1.0);
    using std::exp;
    return exp(-zero_rate(t) * Scalar(t));
  }

 private:
  Eigen::Matrix<Scalar, Eigen::Dynamic, 1> b_;  // [β0, β1, β2, β3]
  double tau1_, tau2_;
};

}  // namespace swaps::curve
