#!/usr/bin/env python3
"""Generate the run_json verb-dispatch arms from the ONE API descriptor `api/api_surface.py`.

Emits `api/run_json_dispatch.gen.inc`, which `api/bundle_api.cpp` #includes inside run_json's try block, so
the stateless JSON seam (portfolio / portfolio_risk / risk / transform) cannot drift from the descriptor the
pybind + Excel bindings also come from. Mirrors `tools/gen_conventions_hpp.py`; gated by verify.sh
(regenerate --stdout + diff). Run: `python3 tools/gen_dispatch.py`; `--stdout` prints for the gate.

The always-on stages (bundle/x0/regularize/calibrate/x) and the irregular `price`/`sample_times` arms stay
hand-written in bundle_api.cpp — their shapes are bespoke.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "api"))
import api_surface as S  # noqa: E402

BANNER = ("// GENERATED by tools/gen_dispatch.py from api/api_surface.py — DO NOT EDIT.\n"
          "// #included inside swaps::api::run_json (bundle_api.cpp); o/sess/reg/out/err/da/json in scope.\n")


def _matrix(resp):
    return (f'      json::array rows;\n'
            f'      for (int i = 0; i < M.rows(); ++i) {{\n'
            f'        json::array row;\n'
            f'        for (int j = 0; j < M.cols(); ++j) row.push_back(M(i, j));\n'
            f'        rows.push_back(row);\n'
            f'      }}\n'
            f'      out["{resp}"] = rows;\n')


def _struct(resp, st):
    fields = []
    for fname, fkind in S.STRUCTS[st]:
        fields.append(f'{{"{fname}", {("da(r." + fname + ")") if fkind == "VEC" else ("r." + fname)}}}')
    return f'      out["{resp}"] = json::object{{{", ".join(fields)}}};\n'


def _call(j, arg):
    a = [arg] if arg else []
    if j["reg"]:
        a.append("reg")
    return f'sess.{j["cpp"]}({", ".join(a)})'


def gen():
    out = [BANNER]
    for j in S.RUN_JSON:
        key, ret = j["key"], j["ret"]
        if j["payload"] == "bool":
            out.append(f'    if (o.contains("{key}") && o.at("{key}").as_bool()) {{\n')
            arg = None
        elif j["payload"] == "book":
            out.append(f'    if (o.contains("{key}")) {{\n')
            arg = f'book_from_json(o.at("{key}"))'
        elif j["payload"] == "source_bundle":
            out.append(f'    if (o.contains("{key}")) {{\n'
                       f'      const auto& t = o.at("{key}").as_object();\n'
                       f'      if (!t.contains("source_bundle")) return err("\'{key}\' requires a '
                       f'\'source_bundle\' object");\n')
            arg = 'bundle_from_json(t.at("source_bundle"))'
        elif j["payload"] == "json":
            # Pass the serialized sub-object to a *_json method that parses its own bespoke sub-schema.
            out.append(f'    if (o.contains("{key}")) {{\n')
            arg = f'json::serialize(o.at("{key}"))'
        else:
            raise SystemExit(f"unknown payload {j['payload']}")
        if ret == "MATRIX":
            out.append(f'      const Eigen::MatrixXd M = {_call(j, arg)};\n' + _matrix(j["resp"]))
        elif ret.startswith("STRUCT:"):
            st = ret.split(":", 1)[1]
            out.append(f'      const {st} r = {_call(j, arg)};\n' + _struct(j["resp"], st))
        else:
            raise SystemExit(f"unknown ret {ret}")
        out.append("    }\n")
    return "".join(out)


STATELESS_BANNER = (
    "// GENERATED by tools/gen_dispatch.py from api/api_surface.py STATELESS_VERBS — DO NOT EDIT.\n"
    "// #included inside swaps::api::run_json(const json::object& o) (bundle_api.cpp), BEFORE the session\n"
    "// stages: the first listed key present in the request selects its verb, which receives the parsed\n"
    "// request object (no second parse — E3-D D11).\n")


def gen_stateless():
    out = [STATELESS_BANNER,
           "    {\n",
           "      struct StatelessVerb {\n",
           "        const char* key;\n",
           "        std::string (*fn)(const json::object&);\n",
           "      };\n",
           "      static constexpr StatelessVerb kVerbs[] = {\n"]
    for v in S.STATELESS_VERBS:
        for k in v["keys"]:
            out.append(f'          {{"{k}", &{v["cpp"]}}},\n')
    out += ["      };\n",
            "      for (const StatelessVerb& v : kVerbs)\n",
            "        if (o.contains(v.key)) return v.fn(o);\n",
            "    }\n"]
    return "".join(out)


def main():
    if len(sys.argv) >= 2 and sys.argv[1] == "--stdout":
        sys.stdout.write(gen())
        return
    if len(sys.argv) >= 2 and sys.argv[1] == "--stdout-stateless":
        sys.stdout.write(gen_stateless())
        return
    path = os.path.join(HERE, "..", "api", "run_json_dispatch.gen.inc")
    with open(path, "w") as f:
        f.write(gen())
    print("wrote api/run_json_dispatch.gen.inc")
    path = os.path.join(HERE, "..", "api", "run_json_stateless.gen.inc")
    with open(path, "w") as f:
        f.write(gen_stateless())
    print("wrote api/run_json_stateless.gen.inc")


if __name__ == "__main__":
    main()
